### ISSUE TITLE
Check stucks on expected state

### ISSUE THREAD

**Issue by pasali** [SystangoTechnologies/commit-message-lint#18] opened 2020-08-26 08:45 UTC
Hi,
We are using this app on our private repositories. It was working like expected untill today. On the all repositories checks stuck at expected state.

**Comment by ajaij** [comment] 2020-08-26 14:42
Happening for me as well, the check is not event getting triggered, after 12 hrs its still showing. I tried disabling and re-enable the branch settings, suspend the app even after these attempts am getting the below msg for both old and new PR's.
 
`Commit Message Lint Expected — Waiting for status to be reported `

Note: Mine is a private org repo

**Comment by sumits-systango** [comment] 2020-08-27 05:15
Private repos should not be a problem anymore. We are taking a look into this.

**Comment by pasali** [comment] 2020-08-28 10:37
@sumits-systango did you have any chance to look at this ?

**Comment by sumits-systango** [comment] 2020-08-31 07:23
The issue is with our cloud provider. This should be fixed today.

**Comment by pdunhamp44** [comment] 2020-08-31 17:14
this is still an issue for us

**Comment by pasali** [comment] 2020-09-02 11:34
It is working now for us.

**Closed as completed** 2020-09-02 13:02 UTC

**Comment by ajaij** [comment] 2021-01-08 05:30
@sumits-systango this issue has re-surfaced again, can you please look into this ?
